### ISSUE TITLE
help configure reload task

### ISSUE THREAD

**Issue by jsaintmaxent** [eapowertools/qs-telemetry-dashboard#37]
Hello,

i try to configure reload task for the metadata but I don't understand how it works.

can you explain me or show me an example?

thanks for your help

**Comment by jsaintmaxent** [comment]
hi,

i try to make connexion rest but i have trouble on backslash, do you have an idea?
![2019-01-03_16h05_48](https://user-images.githubusercontent.com/46328202/50644766-12f14180-0f72-11e9-8a5b-8c989c701f02.png)
thnaks per advance

**Comment by levi-turner** [comment]
I would avoid using the Qlik REST Connector for this flow. If you need guidance on how to make RESTful API calls to Qlik Sense, then [this](https://qliksupport.force.com/articles/000045268) article in the Qlik Support knowledge base is a good introduction.

**Comment by jparis** [comment]
https://help.qlik.com/en-US/sense-developer/November2017/Subsystems/RepositoryServiceAPI/Content/RepositoryServiceAPI/RepositoryServiceAPI-Connect-API-Using-Xrfkey-Headers.htm?_ga=2.21476027.1670729794.1546615160-13112746.1544720976

closing this now because it is out of the scope of the telemetry dashboard.
