### ISSUE TITLE
Install fails with QRS connection

### ISSUE THREAD

**Issue by AndyMarshall1962** [eapowertools/qs-telemetry-dashboard#45]
The installer failed to connect to QRS and I can't understand why. I tracked all the local certs it wanted to use and PowerShell connects just fine. Here is the part of the log that shows the issue. I tried exporting a fresh set of certificates via QMC and ensuring the central node was acting as central just in case that made a difference. I'm totally stumpted as to why it fails. Any suggestion for diagnostics to try?

MSI (s) (E8:80) [12:00:38:896]: Executing op: ActionStart(Name=IsRepositoryRunningAction,,)
Action 12:00:38: IsRepositoryRunningAction. 
MSI (s) (E8:80) [12:00:38:896]: Executing op: CustomActionSchedule(Action=IsRepositoryRunningAction,ActionType=1025,Source=BinaryData,Target=IsRepositoryRunning,)
MSI (s) (E8:78) [12:00:38:911]: Invoking remote custom action. DLL: C:\Windows\Installer\MSIAC3D.tmp, Entrypoint: IsRepositoryRunning
SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSIAC3D.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action CustomActions!CustomActions.CustomActions.IsRepositoryRunning
Cannot install the Telemetry Dashboard as the installer could not contact the 'Qlik Repository Service'.
MSI (s) (E8!A4) [12:00:42:771]: Note: 1: 2205 2:  3: Error 
MSI (s) (E8!A4) [12:00:42:771]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
MSI (s) (E8!A4) [12:00:42:771]: Product: TelemetryDashboard -- Cannot install the Telemetry Dashboard as the installer could not contact the 'Qlik Repository Service'.

**Comment by jparis** [comment]
All the installer does is `Tuple<HttpStatusCode, string> response = MakeQrsRequest("/about", HTTPMethod.GET);` on localhost. Can you hit localhost/qrs/about with the certs, and does it return a good response?

**Comment by AndyMarshall1962** [comment]
I did some tests and the results are both interesting and confusing to me. I used some PS code Levi gave me to test qrs/about. On two servers that I tried localhost failed for both yet one managed the installation. If I tried the short server name they also both failed. If I used the FQDN as Levi's code originally used they both work. 

$Data = Get-Content C:\ProgramData\Qlik\Sense\Host.cfg
$FQDN = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($($Data)))

And then $FQDN is used in the URI. I was surprised that localhost failed with this error.

Invoke-RestMethod : The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

**Comment by jparis** [comment]
Looks like it's trying to do name validation against the certificate. I turn this off by using:
`ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };`

but that is a machine wide setting, so if this is overwritten somewhere due to policy, it won't be able to validate the certificate and it will fail. Might need to turn this off for the install.

**Comment by jparis** [comment]
Oh, it's just a c# piece of code that I have in the installer. but if the system has something different you'll have to override it manually. I'm assuming this would be an IT policy.

**Comment by levi-turner** [comment]
So that we're all on the same page. The schema of the code that I sent along, which I recall working, is:

```
$hdrs = @{}
$hdrs.Add("X-Qlik-Xrfkey","examplexrfkey123")
$hdrs.Add("X-Qlik-User", "UserDirectory=INTERNAL; UserId=sa_api")
$cert = Get-ChildItem -Path "Cert:\CurrentUser\My" | Where {$_.Subject -like '*QlikClient*'}
$Data = Get-Content C:\ProgramData\Qlik\Sense\Host.cfg
$FQDN = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($($Data)))
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]'Ssl3,Tls,Tls11,Tls12' 
Invoke-RestMethod -Uri "https://$($FQDN):4242/qrs/about?xrfkey=examplexrfkey123" -Method Get -Headers $hdrs -ContentType 'application/json' -Certificate $cert
```
If you are, instead, calling `Invoke-RestMethod -Uri "https://localhost:4242/qrs/about?xrfkey=examplexrfkey123" -Method Get -Headers $hdrs -ContentType 'application/json' -Certificate $cert` then yes, the response from PowerShell would be `The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.`

Back to the original issue, as I recall, we needed line `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]'Ssl3,Tls,Tls11,Tls12' ` in PowerShell in order to handle the use of exclusive TLS 1.2 on the OS.

From the Telemetry Installer purposes, do be sure to try the latest release. Technically support for exclusive TLS 1.2 in v2.0.1, I _think_. But we've added some robustness and bug fixes into the latest installer. Just be sure to remove the all the traces of the Telemetry dashboard (App, Tasks) before doing the reinstall to make sure you benefit from the latest and greatest.

Let us know if that does not work.

**Comment by AndyMarshall1962** [comment]
I tried v2.0.3 today and got a string length parameter error. I opened a new issue for this.

**Comment by strelokr** [comment]
Try run msi as QLik sense service user. It's help me

**Comment by AndyMarshall1962** [comment]
Levi helped us over the hump with some manual work.
