### ISSUE TITLE
Telemetry tasks are not visible other than RootAdmin. If visible for Content and Audit admin it says privileges are not enough for reloading.

### ISSUE THREAD

**Issue by Balasupreetha** [eapowertools/qs-telemetry-dashboard#62]

**Comment by levi-turner** [comment]
@Balasupreetha : So that's because the type of task that the we use in **TelemetryDashboard-1-Generate-Metadata** is slightly different from what the default ContentAdmin role is assuming.

Give this a shot:
- Filter: `ExternalProgramTask_*`
- Actions: Read+Update
- Conditions: `((user.roles="ContentAdmin"))`
- Context: Only in QMC

You of course could adjust the conditions to include all Admins (something like `((user.roles like "*Admin*"))`.

**Comment by jparis** [comment]
Closing this.
