### ISSUE TITLE
Generate Metadata task not editable

### ISSUE THREAD

**Issue by DDekov** [eapowertools/qs-telemetry-dashboard#66]
After a fresh install of the current latest version v3.0.0 it is not possible to edit the first reload task in the chain: TelemetryDashboard-1-Generate-Metadata. This task does not have automatic reload schedule so the only possibility is to reload the whole dahsboard is to do it manually at this point.

![image](https://user-images.githubusercontent.com/49514378/55942101-5c75ba80-5c4c-11e9-8b99-8061da42d047.png)

**Comment by cleveranjos** [comment]
It´s documented that this task can´t be edited

**Comment by levi-turner** [comment]
As @cleveranjos mentioned, this is due to limitations in the QMC code in the Qlik Sense product itself. In order to be able to schedule this task, you will need to make API calls. The high level framework for achieving this is documented here: https://github.com/eapowertools/qs-telemetry-dashboard/wiki/Scheduling-TelemetryDashboard-1-Generate-Metadata

I'd encourage contacting Qlik Support or your account team to raise a feature request to have full support for External Program Tasks in the QMC.

At the current juncture there is little that the installer can do itself given this feature gap.

**Comment by levi-turner** [comment]
Tagging as a feature request. Possible work-around toggle in the installer to schedule the task (hourly, daily, weekly). @jparis : Thoughts on how reasonable this is for the installer?

**Comment by DDekov** [comment]
@cleveranjos and @levi-turner thanks a lot for your input. Much appreciated!

**Comment by jparis** [comment]
@levi-turner Not going to add that, and closing this. If we set this in the installer, it'll be virtually impossible to change if people don't know the API calls to make. Either they can set it themselves and control scheduling as they see fit, or use another method (call task/start from another app and schedule that app).
