### ISSUE TITLE
Improve documentation on how to Scheduling TelemetryDashboard 1 Generate Metadata

### ISSUE THREAD

**Issue by simonaubertbd** [eapowertools/qs-telemetry-dashboard#70]
Hello,

Here is the context : 

1/ We cannot edit theTelemetryDashboard 1 Generate Metadata task. That means we cannot have it reloading automatically. There are several issues about it, most closed, such as : 

https://github.com/eapowertools/qs-telemetry-dashboard/issues/66

2/ There is this page that explains how to have a turnaroud with some API : 
https://github.com/eapowertools/qs-telemetry-dashboard/wiki/Scheduling-TelemetryDashboard-1-Generate-Metadata

However, I'm totally unable to understand the documentation. Could it be more detailed and maybe with more screenshots?

Best regards,

Simon

**Comment by jparis** [comment]
It's closed because there's nothing I can do to fix issue 1. This is an internal Qlik Sense Enterprise on Windows issue. Given that the contributors to this project are NOT in R&D, we cannot fix it.

As for part 2, if you can't follow it, I would recommend not trying to go down that path as it's easy to break stuff. The 'easy' way to schedule this is to create an empty app that calls the 'trigger task' from the load script, then schedule that app reload as you would in the QMC.

Closing this issue.
