### ISSUE TITLE
Generate Metadata Task Edit Error

### ISSUE THREAD

**Issue by steveonabike** [eapowertools/qs-telemetry-dashboard#80]
Great tool. Everything seems to be working. When I try to edit the task to put it on a schedule, it throws the attached error. 

![Telemetry_Task_Edit_Issue](https://user-images.githubusercontent.com/55412180/64990838-9d7a9680-d89e-11e9-90c5-a622ce63fe05.JPG)

**Comment by levi-turner** [comment]
@steveonabike : I'm glad to hear things are working well. The error message that you're seeing in the QMC is an artifact of a limitation of the QMC's client code, namely that it doesn't handle External Program Tasks well. The error message aspect is fixed in Qlik Sense June 2019, but that still does not provide a UI to edit the task. In the interim, we have [documented](https://github.com/eapowertools/qs-telemetry-dashboard/wiki/Scheduling-TelemetryDashboard-1-Generate-Metadata) how to schedule the task via API calls.

**Comment by steveonabike** [comment]
@levi-turner Thanks for the great work and the write up.
